
WITH SAMPLES AS (
SELECT PATIENTALERT_ID, ROW_NUMBER() OVER (PARTITION BY PATIENTALERT_ID ORDER BY SOURCE_TIME) AS RN, PATIENTALERT_SAMPLE_ID, SOURCE_TIME, TEXT
FROM (SELECT MIN(PATIENTALERT_SAMPLE_ID) AS PATIENTALERT_SAMPLE_ID, PATIENTALERT_ID, SOURCE_TIME, TEXT FROM PATIENTALERT_SAMPLE
GROUP BY PATIENTALERT_ID, SOURCE_TIME, TEXT)
)


SELECT PATIENTALERT.UNIQUE_DEVICE_IDENTIFIER, PATIENTALERT.IDENTIFIER,
 BEFORE.SOURCE_TIME AS START_TIME, 
 AFTER.SOURCE_TIME AS END_TIME,
 BEFORE.TEXT as TEXT
 FROM SAMPLES BEFORE 
 INNER JOIN PATIENTALERT ON BEFORE.PATIENTALERT_ID = PATIENTALERT.PATIENTALERT_ID
 LEFT OUTER JOIN SAMPLES AFTER ON BEFORE.PATIENTALERT_ID = AFTER.PATIENTALERT_ID AND BEFORE.RN = AFTER.RN - 1
 ORDER BY PATIENTALERT.UNIQUE_DEVICE_IDENTIFIER, PATIENTALERT.IDENTIFIER, START_TIME;
 
 
 
