CREATE TABLE IF NOT EXISTS "OPENICE"."NUMERIC"(
	ID_NUMERIC NUMBER,
	INSTANCE_HANDLE BLOB,
	unique_device_identifier varchar2(255),
	metric_id varchar2(255),
	vendor_metric_id varchar2(255),
	instance_id NUMBER,
	unit_id varchar2(255)
);

ALTER TABLE numeric
ADD CONSTRAINT numeric_pk
  PRIMARY KEY (ID_NUMERIC);


CREATE TABLE IF NOT EXISTS "OPENICE"."NUMERIC_LIFECYCLE"(
	ID_NUMERIC_LIFECYCLE NUMBER,
	ID_NUMERIC NUMBER,
	TIME TIMESTAMP,
	ALIVE BOOLEAN,
	CONSTRAINT FK_NL_NUMERIC_ID
    FOREIGN KEY (ID_NUMERIC)
    REFERENCES NUMERIC (ID_NUMERIC)
);

CREATE TABLE IF NOT EXISTS "OPENICE"."NUMERIC_SAMPLE"(
	ID_NUMERIC_SAMPLE NUMBER,
	ID_NUMERIC NUMBER,
	SOURCE_TIME TIMESTAMP,
	VALUE NUMBER,
	DEVICE_TIME TIMESTAMP,
	PRESENTATION_TIME TIMESTAMP,
	CONSTRAINT FK_NUMERIC_SAMPLE_NUMERIC_ID
    FOREIGN KEY (ID_NUMERIC)
    REFERENCES NUMERIC (ID_NUMERIC)
);