CREATE USER OPENICE2 IDENTIFIED BY OPENICE2
GRANT CREATE SESSION TO OPENICE2 WITH ADMIN OPTION;


CREATE TABLE NUMERIC (
	NUMERIC_ID NUMBER(10) NOT NULL,
	UNIQUE_DEVICE_IDENTIFIER VARCHAR2(64) NOT NULL,
	METRIC_ID VARCHAR2(64) NOT NULL,
	VENDOR_METRIC_ID VARCHAR2(64),
	INSTANCE_ID NUMBER(10) NOT NULL,
	UNIT_ID VARCHAR2(64),
	CONSTRAINT PK_NUMERIC PRIMARY KEY (NUMERIC_ID)
);

CREATE UNIQUE INDEX NUMERIC_UNIQUE_KEYS ON NUMERIC (UNIQUE_DEVICE_IDENTIFIER,METRIC_ID,VENDOR_METRIC_ID,INSTANCE_ID,UNIT_ID);

CREATE SEQUENCE NUMERIC_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE TABLE NUMERIC_LIFECYCLE (
	NUMERIC_LIFECYCLE_ID NUMBER(10) NOT NULL,
	ALIVE NUMBER(10),
	TIME TIMESTAMP(6),
	NUMERIC_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_NUMERIC_LIFECYCLE PRIMARY KEY (NUMERIC_LIFECYCLE_ID)
);

CREATE INDEX FK_LIFECYCLE_NUMERIC ON NUMERIC_LIFECYCLE (NUMERIC_ID);

ALTER TABLE NUMERIC_LIFECYCLE
	ADD FOREIGN KEY (NUMERIC_ID) 
	REFERENCES NUMERIC (NUMERIC_ID);

CREATE SEQUENCE  NUMERIC_LIFECYCLE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE TABLE NUMERIC_SAMPLE (
	NUMERIC_SAMPLE_ID NUMBER(10) NOT NULL,
	SOURCE_TIME TIMESTAMP(6) NOT NULL,
	VALUE NUMBER(10) NOT NULL,
	NUMERIC_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_NUMERIC_SAMPLE PRIMARY KEY (NUMERIC_SAMPLE_ID)
);

CREATE INDEX FK_NUMERIC_ID ON NUMERIC_SAMPLE (NUMERIC_ID);

ALTER TABLE NUMERIC_SAMPLE
	ADD FOREIGN KEY (NUMERIC_ID) 
	REFERENCES NUMERIC (NUMERIC_ID);

CREATE SEQUENCE  NUMERIC_SAMPLE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE OR REPLACE FUNCTION INSERT_UPDATE_NUMERIC(
   UNIQUE_DEVICE_IDENTIFIER IN varchar2,
   METRIC_ID IN varchar2,
   VENDOR_METRIC_ID IN varchar2,
   INSTANCE_ID IN decimal,
   UNIT_ID IN varchar2
   
) 
RETURN NUMBER
AS
NUMERIC_ID NUMBER(10);
BEGIN
 SELECT NUMERIC.NUMERIC_ID INTO insert_update_numeric.NUMERIC_ID FROM NUMERIC 
 	WHERE NUMERIC.UNIQUE_DEVICE_IDENTIFIER = insert_update_numeric.UNIQUE_DEVICE_IDENTIFIER AND 
 		  NUMERIC.METRIC_ID = insert_update_numeric.METRIC_ID AND 
 		  ((NUMERIC.VENDOR_METRIC_ID IS NULL AND insert_update_numeric.VENDOR_METRIC_ID IS NULL) OR NUMERIC.VENDOR_METRIC_ID = insert_update_numeric.VENDOR_METRIC_ID) AND
 		  NUMERIC.INSTANCE_ID = insert_update_numeric.INSTANCE_ID AND 
 		  ((NUMERIC.UNIT_ID IS NULL AND insert_update_numeric.UNIT_ID IS NULL) OR NUMERIC.UNIT_ID = insert_update_numeric.UNIT_ID);
 RETURN insert_update_numeric.NUMERIC_ID; 		  
 EXCEPTION WHEN NO_DATA_FOUND THEN
 BEGIN
    SELECT NUMERIC_SEQ.nextval into insert_update_numeric.NUMERIC_ID FROM dual;
    INSERT INTO NUMERIC (NUMERIC_ID, UNIQUE_DEVICE_IDENTIFIER, METRIC_ID, VENDOR_METRIC_ID, INSTANCE_ID, UNIT_ID) VALUES (insert_update_numeric.NUMERIC_ID, UNIQUE_DEVICE_IDENTIFIER, METRIC_ID, VENDOR_METRIC_ID, INSTANCE_ID, UNIT_ID);
    COMMIT;
    RETURN insert_update_numeric.NUMERIC_ID;
 END;
END;
/
CREATE TABLE TECHNICALALERT (
	TECHNICALALERT_ID NUMBER(10) NOT NULL,
	UNIQUE_DEVICE_IDENTIFIER VARCHAR2(64) NOT NULL,
	IDENTIFIER VARCHAR2(256) NOT NULL,
	CONSTRAINT PK_TECHNICALALERT PRIMARY KEY (TECHNICALALERT_ID)
);

CREATE UNIQUE INDEX TECHNICALALERT_UNIQUE_KEYS ON TECHNICALALERT (UNIQUE_DEVICE_IDENTIFIER,IDENTIFIER);

CREATE SEQUENCE TECHNICALALERT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE TABLE TECHNICALALERT_LIFECYCLE (
	TECHNICALALERT_LIFECYCLE_ID NUMBER(10) NOT NULL,
	ALIVE NUMBER(10),
	TIME TIMESTAMP(6),
	TECHNICALALERT_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_TECHNICALALERT PRIMARY KEY (TECHNICALALERT_LIFECYCLE_ID)
);

CREATE INDEX FK_LIFECYCLE_TECHNICALALERT ON TECHNICALALERT_LIFECYCLE (TECHNICALALERT_ID);

ALTER TABLE TECHNICALALERT_LIFECYCLE
	ADD FOREIGN KEY (TECHNICALALERT_ID) 
	REFERENCES TECHNICALALERT (TECHNICALALERT_ID);

CREATE SEQUENCE  TECHNICALALERT_LIFECYCLE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE TABLE TECHNICALALERT_SAMPLE (
	TECHNICALALERT_SAMPLE_ID NUMBER(10) NOT NULL,
	TECHNICALALERT_ID NUMBER(10) NOT NULL,
	SOURCE_TIME TIMESTAMP(6) NOT NULL,
	TEXT VARCHAR2(256),
	CONSTRAINT PK_TECHNICALALERT_SAMPLE PRIMARY KEY (TECHNICALALERT_SAMPLE_ID)
);

CREATE INDEX FK_TECHNICALALERT_ID ON TECHNICALALERT_SAMPLE (TECHNICALALERT_ID);

ALTER TABLE TECHNICALALERT_SAMPLE
	ADD FOREIGN KEY (TECHNICALALERT_ID) 
	REFERENCES TECHNICALALERT (TECHNICALALERT_ID);

CREATE SEQUENCE  TECHNICALALERT_SAMPLE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE OR REPLACE FUNCTION INSERT_UPDATE_TECHNICALALERT(
   UNIQUE_DEVICE_IDENTIFIER IN varchar2,
   IDENTIFIER IN varchar2
) 
RETURN NUMBER
AS
TECHNICALALERT_ID NUMBER(10);
BEGIN
 SELECT TECHNICALALERT.TECHNICALALERT_ID INTO insert_update_TECHNICALALERT.TECHNICALALERT_ID FROM TECHNICALALERT 
 	WHERE TECHNICALALERT.UNIQUE_DEVICE_IDENTIFIER = insert_update_TECHNICALALERT.UNIQUE_DEVICE_IDENTIFIER AND 
 		  TECHNICALALERT.IDENTIFIER = insert_update_TECHNICALALERT.IDENTIFIER;
 RETURN insert_update_TECHNICALALERT.TECHNICALALERT_ID; 		  
 EXCEPTION WHEN NO_DATA_FOUND THEN
 BEGIN
    SELECT TECHNICALALERT_SEQ.nextval into insert_update_TECHNICALALERT.TECHNICALALERT_ID FROM dual;
    INSERT INTO TECHNICALALERT (TECHNICALALERT_ID, UNIQUE_DEVICE_IDENTIFIER, IDENTIFIER) VALUES (insert_update_TECHNICALALERT.TECHNICALALERT_ID, insert_update_TECHNICALALERT.UNIQUE_DEVICE_IDENTIFIER, insert_update_TECHNICALALERT.IDENTIFIER);
    COMMIT;
    RETURN insert_update_TECHNICALALERT.TECHNICALALERT_ID;
 END;
END;
/
CREATE TABLE PATIENTALERT (
	PATIENTALERT_ID NUMBER(10) NOT NULL,
	UNIQUE_DEVICE_IDENTIFIER VARCHAR2(64) NOT NULL,
	IDENTIFIER VARCHAR2(256) NOT NULL,
	CONSTRAINT PK_PATIENTALERT PRIMARY KEY (PATIENTALERT_ID)
);

CREATE UNIQUE INDEX PATIENTALERT_UNIQUE_KEYS ON PATIENTALERT (UNIQUE_DEVICE_IDENTIFIER,IDENTIFIER);

CREATE SEQUENCE PATIENTALERT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE TABLE PATIENTALERT_LIFECYCLE (
	PATIENTALERT_LIFECYCLE_ID NUMBER(10) NOT NULL,
	ALIVE NUMBER(10),
	TIME TIMESTAMP(6),
	PATIENTALERT_ID NUMBER(10) NOT NULL,
	CONSTRAINT PK_PATIENTALERT_LIFECYCLE PRIMARY KEY (PATIENTALERT_LIFECYCLE_ID)
);

CREATE INDEX FK_LIFECYCLE_PATIENTALERT ON PATIENTALERT_LIFECYCLE (PATIENTALERT_ID);

ALTER TABLE PATIENTALERT_LIFECYCLE
	ADD FOREIGN KEY (PATIENTALERT_ID) 
	REFERENCES PATIENTALERT (PATIENTALERT_ID);

CREATE SEQUENCE  PATIENTALERT_LIFECYCLE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE TABLE PATIENTALERT_SAMPLE (
	PATIENTALERT_SAMPLE_ID NUMBER(10) NOT NULL,
	PATIENTALERT_ID NUMBER(10) NOT NULL,
	SOURCE_TIME TIMESTAMP(6) NOT NULL,
	TEXT VARCHAR2(256),
	CONSTRAINT PK_PATIENTALERT_SAMPLE PRIMARY KEY (PATIENTALERT_SAMPLE_ID)
);

CREATE INDEX FK_PATIENTALERT_ID ON PATIENTALERT_SAMPLE (PATIENTALERT_ID);

ALTER TABLE PATIENTALERT_SAMPLE
	ADD FOREIGN KEY (PATIENTALERT_ID) 
	REFERENCES PATIENTALERT (PATIENTALERT_ID);

CREATE SEQUENCE  PATIENTALERT_SAMPLE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE OR REPLACE FUNCTION INSERT_UPDATE_PATIENTALERT(
   UNIQUE_DEVICE_IDENTIFIER IN varchar2,
   IDENTIFIER IN varchar2
) 
RETURN NUMBER
AS
PATIENTALERT_ID NUMBER(10);
BEGIN
 SELECT PATIENTALERT.PATIENTALERT_ID INTO insert_update_PATIENTALERT.PATIENTALERT_ID FROM PATIENTALERT 
 	WHERE PATIENTALERT.UNIQUE_DEVICE_IDENTIFIER = insert_update_PATIENTALERT.UNIQUE_DEVICE_IDENTIFIER AND 
 		  PATIENTALERT.IDENTIFIER = insert_update_PATIENTALERT.IDENTIFIER;
 RETURN insert_update_PATIENTALERT.PATIENTALERT_ID; 		  
 EXCEPTION WHEN NO_DATA_FOUND THEN
 BEGIN
    SELECT PATIENTALERT_SEQ.nextval into insert_update_PATIENTALERT.PATIENTALERT_ID FROM dual;
    INSERT INTO PATIENTALERT (PATIENTALERT_ID, UNIQUE_DEVICE_IDENTIFIER, IDENTIFIER) VALUES (insert_update_PATIENTALERT.PATIENTALERT_ID, insert_update_PATIENTALERT.UNIQUE_DEVICE_IDENTIFIER, insert_update_PATIENTALERT.IDENTIFIER);
    COMMIT;
    RETURN insert_update_PATIENTALERT.PATIENTALERT_ID;
 END;
END;
/
show errors





